from .policy_system_prompt import GLOBAL_POLICY
from .task_rules import CAFE_TASK_RULES, GENERAL_TASK_RULES
from .output_format import CAFE_RECOMMENDATION_FORMAT, PREFERENCE_EXTRACTION_FORMAT
from .guide_instructions import (
    ALREADY_RECOMMENDED_INSTRUCTION,
    READY_TO_RECOMMEND_INSTRUCTION,
    QUIZ_RESULT_CONFIRMATION_INSTRUCTION,
    get_confirmation_instruction,
    PREFERENCE_EXTRACTION_TASK,
    PREFERENCE_EXTRACTION_RULES
)

__all__ = [
    "GLOBAL_POLICY",
    "CAFE_TASK_RULES",
    "GENERAL_TASK_RULES",
    "CAFE_RECOMMENDATION_FORMAT",
    "PREFERENCE_EXTRACTION_FORMAT",
    "ALREADY_RECOMMENDED_INSTRUCTION",
    "READY_TO_RECOMMEND_INSTRUCTION",
    "QUIZ_RESULT_CONFIRMATION_INSTRUCTION",
    "get_confirmation_instruction",
    "PREFERENCE_EXTRACTION_TASK",
    "PREFERENCE_EXTRACTION_RULES"
]
